# -*- coding: utf-8 -*-
"""Bieliaieva_DA8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jspoO1tuCUppchxHh5k_L36jvuclqLBh
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans

# Region_of_Ukraine                       |`str`|      Область України та місто Київ.
# Year                                    |`int`|      Рік, за який наведені економічні показники (2022, 2023).
# Region                                  |`str`|      Географічний регіони: `North`, `South`, `East`, `West`.
# Exports(thsd.USD)                       |`float`|    Обсяг експорту в тис. дол.
# Imports(thsd.USD)                       |`float`|    Обсяг імпорту в тис.дол.
# Profit_loss_enterprises(mln.UAH)        |`float`|    Чистий прибуток (збиток) підприємств за областями в загалом в млн. грн.
# Turnover_of_business_entities(thsd.UAH) |`float`|    Обсяг реалізованої продукції (товарів, послуг) суб’єктів господарювання за регіонами в тис. грн.
# Capital_investments(thsd.UAH)           |`int`|      Капітальні інвестиції за регіонами в тис. грн.
# Latitude                                |`float`|    Географічна широта для мапи.
# Longitude                               |`float`|    Географічна довгота для мапи.

# Завантажимо дані
df = pd.read_csv('data.csv', sep=';')

df.info()

df.describe()

missing_data = df.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

st.set_page_config(
    page_title="Економічний дашборд",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Інтерактивна панель для економічного аналізу областей України'
    }
)

# Бічна панель / SIDEBAR
st.sidebar.title("Панель фільтрації")

# Фільтри
selected_year = st.sidebar.selectbox("Рік", sorted(df["Year"].unique()))
selected_region = st.sidebar.multiselect("Регіон", df["Region"].unique(), default=df["Region"].unique())

selected_max_capital_investment = st.sidebar.slider(
    "Максимальний обсяг реалізованої продукції (товарів, послуг) суб’єктів господарювання",
    min_value=int(df["Turnover_of_business_entities(thsd.UAH)"].min()),
    max_value=int(df["Turnover_of_business_entities(thsd.UAH)"].max()),
    value=int(df["Turnover_of_business_entities(thsd.UAH)"].max()),
    step=100000000
)

# Чекбокси для відображення
show_map = st.sidebar.checkbox("🗺 Показати карту областей")

# Перемикач графіків
chart_option = st.sidebar.radio(
    "📈 Оберіть графік для перегляду:",
    [
        "Стовпчаста діаграма: Експорт vs Імпорт",
        "Boxplot чистий прибуток (збиток) підприємств в областях України за географічними регіонами",
        "Теплова карта кореляцій"
    ]
)

# Інформаційний блок
st.sidebar.markdown("---")
st.sidebar.markdown(" **Інструкція**: \nФільтруйте дані за параметрами і переглядайте графіки та таблиці на панелі праворуч.")
st.sidebar.markdown(" **Автор**: Bieliaieva_Daria")

# Фільтрація

df_filtered = df[
    (df["Year"] == selected_year) &
    (df["Region"].isin(selected_region))&
    (df["Turnover_of_business_entities(thsd.UAH)"] <= selected_max_capital_investment)
]

# Блок регресії
st.sidebar.markdown("Побудова регресії")
numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()

reg_x = st.sidebar.selectbox("Оберіть змінну X", numeric_columns, index=0)
reg_y = st.sidebar.selectbox("Оберіть змінну Y", numeric_columns, index=1)
show_regression = st.sidebar.checkbox("Показати регресійну модель")

# Основна панель

st.title("📊 Економічний дашборд компаній")
st.subheader(f"🔍 Відфільтровано {df_filtered.shape[0]} областей")

# Кнопка завантаження CSV
csv = df_filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="⬇️ Завантажити CSV",
    data=csv,
    file_name="filtered_regions.csv",
    mime="text/csv"
)

# Інтерактивна таблиця результатів

st.subheader("Оберіть, які стовпці таблиці відображати")

all_columns = df_filtered.columns.tolist()
default_columns = ["Region_of_Ukraine", "Region", "Exports(thsd.USD)", "Imports(thsd.USD)", "Capital_investments(thsd.UAH)"]

selected_columns = st.multiselect(
    "Оберіть стовпці для перегляду",
    options=all_columns,
    default=[col for col in default_columns if col in all_columns]
)

if selected_columns:
    st.dataframe(df_filtered[selected_columns])
else:
    st.info("Оберіть хоча б один стовпець, щоб побачити таблицю.")


# Карта компаній
if show_map:
    st.subheader("🗺 Географія областей")
    map_data = df_filtered[["Latitude", "Longitude"]].dropna().rename(
        columns={"Latitude": "latitude", "Longitude": "longitude"}
    )
    if not map_data.empty:
        st.map(map_data)
    else:
        st.warning("Немає доступних координат для побудови карти.")


# Відображення обраного графіка
if chart_option == "Стовпчаста діаграма: Експорт vs Імпорт":
    st.subheader("📊 Стовпчаста діаграма: Експорт vs Імпорт по областях України")

    # Вибираємо потрібні колонки
    df_bar = df_filtered[["Region_of_Ukraine", "Exports(thsd.USD)", "Imports(thsd.USD)"]].dropna()

    # Перетворюємо в long-формат для Altair
    df_melted = df_bar.melt(id_vars="Region_of_Ukraine",
                            value_vars=["Exports(thsd.USD)", "Imports(thsd.USD)"],
                            var_name="Тип",
                            value_name="Значення")

    chart = alt.Chart(df_melted).mark_bar().encode(
        x=alt.X("Region_of_Ukraine:N", sort='-y', title="Область"),
        y=alt.Y("Значення:Q", title="Тис. USD"),
        color=alt.Color("Тип:N", title="Показник"),
        tooltip=["Region_of_Ukraine:N", "Тип:N", "Значення:Q"]
    ).properties(
        width=800,
        height=500,
        title="Експорт та Імпорт по областях України"
    )

    st.altair_chart(chart, use_container_width=True)

elif chart_option == "Boxplot чистий прибуток (збиток) підприємств в областях України за географічними регіонами":
    st.subheader("📊 Boxplot чистий прибуток (збиток) підприємств в областях України за географічними регіонами")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.boxplot(data=df_filtered, x="Region", y="Profit_loss_enterprises(mln.UAH)", ax=ax)
    ax.set_title("Розподіл чистого прибутку (збитку) підприємств в областях України за географічними регіонами")
    st.pyplot(fig)

elif chart_option == "Теплова карта кореляцій":
    st.subheader("📊 Теплова карта кореляцій")
    numeric_cols = df_filtered.select_dtypes(include=[np.number])
    corr = numeric_cols.corr()
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", ax=ax)
    ax.set_title("Кореляційна матриця числових показників")
    st.pyplot(fig)

# Побудова регресійної моделі
if show_regression:
    st.subheader(f"📈 Лінійна регресія: {reg_y} ~ {reg_x}")

    df_reg = df_filtered[[reg_x, reg_y]].dropna()

    if df_reg.shape[0] >= 2:
        model = LinearRegression()
        model.fit(df_reg[[reg_x]], df_reg[reg_y])
        y_pred = model.predict(df_reg[[reg_x]])

        coef = model.coef_[0]
        intercept = model.intercept_
        r2 = model.score(df_reg[[reg_x]], df_reg[reg_y])

        st.markdown(f"**Коефіцієнт нахилу (β):** {coef:.4f}")
        st.markdown(f"**Зсув (intercept):** {intercept:.4f}")
        st.markdown(f"**R²:** {r2:.4f}")

        fig, ax = plt.subplots(figsize=(8, 5))
        sns.scatterplot(data=df_reg, x=reg_x, y=reg_y, ax=ax)
        sns.lineplot(x=df_reg[reg_x], y=y_pred, color='red', ax=ax)
        ax.set_title(f"Регресія {reg_y} ~ {reg_x}")
        st.pyplot(fig)
    else:
        st.warning("Недостатньо даних для побудови регресії.")